package vu.lt.mybatis.model;

public class Cars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARS.ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARS.NAME
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CARS.DRIVER_ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    private Integer driverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARS.ID
     *
     * @return the value of PUBLIC.CARS.ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARS.ID
     *
     * @param id the value for PUBLIC.CARS.ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARS.NAME
     *
     * @return the value of PUBLIC.CARS.NAME
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARS.NAME
     *
     * @param name the value for PUBLIC.CARS.NAME
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CARS.DRIVER_ID
     *
     * @return the value of PUBLIC.CARS.DRIVER_ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CARS.DRIVER_ID
     *
     * @param driverId the value for PUBLIC.CARS.DRIVER_ID
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }
}