package vu.lt.mybatis.dao;

import java.util.List;
import vu.lt.mybatis.model.Cars;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    int insert(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    Cars selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    List<Cars> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Sun Apr 28 09:01:46 EEST 2019
     */
    int updateByPrimaryKey(Cars record);

    List<Cars> getCarsByDriversID(Integer id);
}